export const CHANGE_PAGE_NO = "CHANGE_PAGE_NO";
export const SORT_BY_AMOUNT = "SORT_BY_AMOUNT";
export const SORT_BY_PID = "SORT_BY_PID";
export const SORT_BY_EMAIL = "SORT_BY_EMAIL";
export const FILTER_PAYMENT_STATUS = "FILTER_PAYMENT_STATUS";
export const FILTER_DATERANGE = "FILTER_DATERANGE";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
